server:
  port: 8080

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.availability.AvailabilityProbesAutoConfiguration
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # --- 1. ADMIN SERVICE ---
        - id: admin-service
          uri: http://admin-service:8081
          predicates:
            - Path=/admin/**, /auth/**

        # --- 2. BLOG SERVICE ---
        - id: blog-service
          uri: http://blog-service:8082
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- 3. EMAIL SERVICE ---
        - id: email-service
          uri: http://email-service:8083
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- 4. IMAGE SERVICE ---
        - id: image-service
          uri: http://image-service:8084
          predicates:
            - Path=/image/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- 5. SHOP SERVICE ---
        - id: shop-service
          uri: http://shop-service:8085
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- SWAGGER AGGREGATION ROUTES ---
        - id: admin-docs
          uri: http://admin-service:8081
          predicates:
            - Path=/admin-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: blog-docs
          uri: http://blog-service:8082
          predicates:
            - Path=/blog-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: email-docs
          uri: http://email-service:8083
          predicates:
            - Path=/email-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: image-docs
          uri: http://image-service:8084
          predicates:
            - Path=/image-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: shop-docs
          uri: http://shop-service:8085
          predicates:
            - Path=/shop-service/v3/api-docs/**
          filters:
            - StripPrefix=1


# --- SÃ„KERHET ---
jwt:
  secret: ${JWT_SECRET}

# --- HEALTH CHECKS ---
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: false
    readinessstate:
      enabled: false

# --- SWAGGER UI CONFIGURATION ---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 1. Admin Service
        url: /admin-service/v3/api-docs
      - name: 2. Blog Service
        url: /blog-service/v3/api-docs
      - name: 3. Email Service
        url: /email-service/v3/api-docs
      - name: 4. Image Service
        url: /image-service/v3/api-docs
      - name: 5. Shop Service
        url: /shop-service/v3/api-docs
  api-docs:
    path: /v3/api-docs