server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # --- ADMIN (auth endpoints - publika, hanteras av filtret) ---
        - id: admin-service
          uri: http://admin-service:8081
          predicates:
            - Path=/api/admin/**, /api/auth/**, /actuator/**

        # --- SHOP (Cart, Customer, Product) ---
        - id: shop-service
          uri: http://shop-service:8085
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- BLOG ---
        - id: blog-service
          uri: http://blog-service:8082
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- IMAGE ---
        - id: image-service
          uri: http://image-service:8084
          predicates:
            - Path=/image/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- EMAIL ---
        - id: email-service
          uri: http://email-service:8083
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
            - JwtAuthentication

        # --- SWAGGER DOCS ---
        - id: admin-docs
          uri: http://admin-service:8081
          predicates:
            - Path=/admin-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: shop-docs
          uri: http://shop-service:8085
          predicates:
            - Path=/shop-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: blog-docs
          uri: http://blog-service:8082
          predicates:
            - Path=/blog-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: image-docs
          uri: http://image-service:8084
          predicates:
            - Path=/image-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: email-docs
          uri: http://email-service:8083
          predicates:
            - Path=/email-service/v3/api-docs/**
          filters:
            - StripPrefix=1

# JWT Secret f√∂r token-validering
jwt:
  secret: ${JWT_SECRET}